export enum authErrorMessages {
  INVALID_THIRD_PARTY_AUTHENTICATION = 'Invalid third party authentication.',
  EMAIL_ALREADY_REGISTERED = 'Email is already registered.',
  MISSING_AUTH_TOKEN = 'Authorization token is missing.',
  INVALID_AUTH_TOKEN = 'Authorization token is invalid.',
  UNAUTHORIZED_ACCESS = 'You are not authorized to perform this action.',
  MISSING_REGISTRATION_FIELD = 'Required registration fields are missing.',
  VALIDATION_FAIL = 'fail the authentication format please see the details',
  DUPLICATION_EMAIL = 'this email has been registered',
  UNKNOWN_ERROR = 'registration fail due to unknown reason',
  JWT_SECRET_NOT_SET = 'JWT secret not set, please check JWT_SECRET environment variable',
  JWT_TOKEN_GENERATION_ERROR = 'Error generating login token',
  JWT_CONFIG_ERROR = 'JWT configuration error',
  USERNAME_ALREADY_TAKEN = 'Username already taken',
  USER_NOT_FOUND = 'User not found',
  THIRD_PARTY_AUTH_ERROR = 'Third-Party registration failed. You can try again or email registration',
}
