name: Install Frontend Dependencies

on:
  push:
    branches:
      - devops-ben

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # ✅ 改成符合 Next.js 要求的版本
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build
