name: Run build test

on:
  push:
    branches:
      - devops-ben

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build
