name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - dev
      - test/-devops-CICD-dev-branch-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
         
      - name: Terraform Apply
        run:
         terraform apply -auto-approve
  
