name: test

on:
  push:
    branches:
      - devops-ben
      - test/-devops-CICD-dev-branch-test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
